# These are supported funding model platforms

github: # https://github.com/maurobernal
youtube: # https://youtube.com/c/maurobernal
twitch: # https://twitch.com/maurobernal
facebook: #http://facebook.com/maurobernalgaming
