//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalSend.App_Data.PORTALSEND
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public int tem_id { get; set; }
        public string tem_titulo { get; set; }
        public string tem_cuerpo { get; set; }
    }
}
